<?php

namespace SimplonR\PlateformeBundle\Repository;

/**
 * ApplicantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicantRepository extends \Doctrine\ORM\EntityRepository
{
}
