simplon_r_plateforme:
    resource: "@SimplonRPlateformeBundle/Controller/"
    type:     annotation
    prefix:   /


applicants:
    type: rest
    resource: "@SimplonRPlateformeBundle/Controller/ApplicantController.php"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
